### ISSUE TITLE
Failed: Error: Insufficient balance. You may need to wrap Ether.

### ISSUE THREAD

**Issue by botoxparty** [ProjectOpenSea/opensea-js#102]
Hey,

I'm trying to implement the SDK for a custom implementation but when I try to add a bid to an asset using `createBuyOrder` I get this message: 

Failed: Error: Insufficient balance. You may need to wrap Ether.

I definitely have enough ETH and WETH in my wallet to make the transaction. Is there something i'm missing here?

Just following the documentation. This is the sample of my call:

```
      const buyOrder = await seaport.createBuyOrder({
        asset: {
          tokenId: asset.tokenId,
          tokenAddress: asset.tokenAddress,
          schemaName: asset.schemaName
        },
        startAmount: 0.51,
        accountAddress: accountAddress[0],
      });

**Comment by eltyweb** [comment]
Hi @botoxparty,
I fixed this error by giving the token contract address to the createBuyOrder method.
```
if (process.env.NODE_ENV === 'production') {
  const address = '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'; // WETH contract address on mainnet
} else {
  const address = '0xc778417e063141139fce010982780140aa0cd5ab'; // WETH contract address on rinkeby
}

const buyOrder = await seaport.createBuyOrder({
  asset: {
    tokenId: asset.tokenId,
    tokenAddress: asset.tokenAddress,
    schemaName: asset.schemaName
  },
  startAmount: 0.51,
  accountAddress: accountAddress[0],
  paymentTokenAddress: address
});
```

You can also retrieve available paymentTokenAddress with 
`const tokens = (await seaport.api.getPaymentTokens()).tokens;`

getPaymentTokens() allows you to filter the response with a query parameter
`const tokens = (await seaport.api.getPaymentTokens({ symbol: 'WETH' })).tokens;`

I hope this will help you !

**Comment by CrazyOptimist** [comment]
You need to wrap your ETH to wETH first. If you are using Rinkeby network, use uniswap or send your ETH directly to the wETH contract address. You can find out the wETH contract address by searching in the Rinkeby explorer. But here it is, for you :)
https://rinkeby.etherscan.io/address/0xc778417E063141139Fce010982780140Aa0cD5Ab

**Comment by esteban-OpenSea** [comment]
Hello, are you still having issues with this?

**Comment by esteban-OpenSea** [comment]
Checking in again on this. You need wrapped eth (WETH) to bid on items. Wrap your eth first and then bid.

**Comment by raelix** [comment]
I'm still having this issue even if I wrapped the eth to weth and passed the address, any suggestion?
