### ISSUE TITLE
createBuyOrder() Request Gets Throttled After One Bid

### ISSUE THREAD

**Issue by MetalGear-cmd** [ProjectOpenSea/opensea-js#544]
Hey Guys,
I have been trying to makes Bids on Assets using the SDK, as soon as I place a Bid on One Assets the request, gets throttled for ONE HOUR, before I plce a Bid using the createBuyOrder(), I can make 4 API calls per Sec. Like normally.  As soon as I make Bid the reuest gets throttled for One Hour. After this error appears I can no longer make any other calls like fetching listings or offers etc which I can successfully 4 per second before executing the createBuyOrder(). 
This error started Appearing since the Programmatic Order Submission was first disabled on 20th May, and since then it has been appearing even after the programmatic order submission fully functional.
This is the error which I am getting, 

Making Bid on asset: "oracolo.eth"
Already approved enough currency for trading
Error: API Error 429: Message: {"detail":"Request was throttled. Expected available in 3586 seconds."}
    at OpenSeaAPI.<anonymous> (C:\...\...\...\...\node_modules\opensea-js\src\api.ts:454:11)
    at step (C:\...\...\...\...\node_modules\opensea-js\lib\api.js:63:23)
    at Object.next (C:\...\...\...\...\node_modules\opensea-js\lib\api.js:44:53)
    at fulfilled (C:\...\...\...\...\node_modules\opensea-js\lib\api.js:35:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Making Bid on asset: "virtualgym.eth"
Already approved enough currency for trading
Error: API Error 429: Message: {"detail":"Request was throttled."}
    at OpenSeaAPI.<anonymous> (C:\...\...\...\...\node_modules\opensea-js\src\api.ts:454:11)
    at step (C:\...\...\...\...\node_modules\opensea-js\lib\api.js:63:23)
    at Object.next (C:\...\...\...\...\node_modules\opensea-js\lib\api.js:44:53)
    at fulfilled (C:\...\...\...\...\node_modules\opensea-js\lib\api.js:35:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

I know this has something to do with the recent changes the team has made to the SDK, but it has been 12 Days and there has been no fix, anyone who knows a fix please help me.
Thanks

**Comment by esteban-OpenSea** [comment]
This might have happened when we were having site issues that affected the API. Are you still having this issue? If so, reach out to us on discord or open up a zendesk ticket so we can look into your key.

**Comment by SourceSafe** [comment]
Hi Esteban - I have the same issue.

When I createBuyOrder() using the SDK all of my calls are now giving me 429 errors.

This is irrespective of whether order submission is enabled or not. This has been an issue for approx 2 weeks and is still a problem when order submission is enabled and GREEN. But yeah I appreciate that the status has been down a lot but even when it's green and everyone else is bidding it looks like we get 429's but before it was ok.

My keys used to work perfectly.

I have submitted a ticket, please take a look :-

563139

Please take look thank you.

**Comment by aster2709** [comment]
same for me. my request to the following method is getting throttled as well. this was not the case some days ago.

- createBuyOrder
- createSellOrder
- createBundleBuyOrder

all of these are getting throttled. I'm sure the request structuring is correct from my end!

**Comment by ft1-1** [comment]
Same issue for me, this doesn't appear to have been resolved with the latest maintenance.

**Comment by SourceSafe** [comment]
Hey esteban-OpenSea
Are users being throttled  intentionally? I've had this issue for over 3 weeks now. Even when order submission is enabled and status is green. Is this a bug or have our keys been throttled intentionally. How can I get a key to you for you to investigate?

Can you use the Ticket #563139 that I submitted for you to investigate? It has the keys that are affected.

**Comment by Moutoun** [comment]
@esteban-OpenSea , The same thing for me, getting throttled after 1 request.. My API key was working great before

**Comment by shawns19** [comment]
I'm getting 500 API errors when creating bids, can't even create the bid programmatically but works manually with the same account @esteban-OpenSea

**Comment by MetalGear-cmd** [comment]
Even after the most recent maintenance, this issue is still there which means that Dev team has not fixed it yet, and will most probably won't. Garbage Support, worthless service. Thanks alot OS for wasting our time.

Making Bid on asset: "steadyboombibi.eth"
Already approved enough currency for trading
Successfully Placed Bid!

Making Bid on asset: "choise.eth"
Already approved enough currency for trading
Error: API Error 429: Message: {"detail":"Request was throttled. Expected available in 3586 seconds."}
    at OpenSeaAPI.<anonymous> (D:\node_modules\opensea-js\src\api.ts:454:11)
    at step (D:\node_modules\opensea-js\lib\api.js:63:23)
    at Object.next (D:\node_modules\opensea-js\lib\api.js:44:53)
    at fulfilled (D:\node_modules\opensea-js\lib\api.js:35:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)  

Not expecting this to be fixed.
Peace

**Comment by Moutoun** [comment]
Yeah, not working at all..

**Comment by SourceSafe** [comment]
> de_modules\opensea-js\lib\api.js:35:58)
> at processTicksA

So are you saying that on one wallet you cab bid OK but on others you get the 429's?

**Comment by SourceSafe** [comment]
So this is a WALLET issue more than it is a key issue? DO keys now have wallet affinity perhaps? On my key request i gave a signed wallet - do we think this is the wallet that is bound to the key perhaps? OR am i reading too much into  this?

**Comment by SourceSafe** [comment]
Are bids from the SDK being throttled intentionally. For example can you answer this simple question (please do so if you can)-
Q: Are bids being 429's intentionally. Wallets and keys that used to work no longer work- why is this ? is this a bug or is this an intentional  throttle. ? An answer please ASAP this has been outstanding for over 3 weeks.

**Comment by MetalGear-cmd** [comment]
No fix till now, and I am guessing there won't be any.
Thanks a lot Opensea. BTW it's a whole month now.

**Comment by SourceSafe** [comment]
Problem here is your wallet is banned - your keys i believe have wallet affinity - face up to it buddy - they don’t want to business .

**Comment by SourceSafe** [comment]
If you get 429 you are all structured well and they are throttling you regardless
