### ISSUE TITLE
Wyvern orders posted to the API are deprecated, except for shared storefront orders

### ISSUE THREAD

**Issue by Lebski** [ProjectOpenSea/opensea-js#610]
When creating an order with `createFactorySellOrders`, I get the Error: 
```
"['Wyvern orders posted to the API are deprecated, except for shared storefront orders']"
```

How can I use the new API? 

I'm using opensea-js version 4.0.3

**Comment by allan-hb** [comment]
use another function, createSellOrders,try it

**Comment by Meloneat** [comment]
Hi, the problem confused you has been solved ?
Wha't the point?

**Comment by carlosbalsas** [comment]
Same problem here, when I try to list an item throw API.

**Comment by Lebski** [comment]
Aparently `createFactorySellOrders` is not supported anymore. I haven't found a solution for this. 

Currently I'm trying to use an ERC721 to act as a Factory but I got another weird error in the Frontend when I try to buy the Asset. ([InvalidRestrictedOrder](https://rinkeby.etherscan.io/address/0x00000000006c3852cbef3e08e8df289169ede581#code#F38#L18))

**Comment by cto-aarchik** [comment]
same error while `createSellOrder `

**Comment by danobrown** [comment]
Trying to place a bid on https://opensea.io/ and getting the same error.

Request URL: https://api.opensea.io/wyvern/v1/orders/post/

Response: "['Wyvern orders posted to the API are deprecated, except for shared storefront orders']"

**Comment by cto-aarchik** [comment]
> ```js
> OpenSeaSDK
> ```

i try this but not working

**Comment by andremfaria** [comment]
Same problem here. Also I get an "execution reverted" while creating the sell order via https://testnets.opensea.io/assets/rinkeby/<factory_contract_address>/0/sell. I don't know if the problem is related. Some days ago it all works smoothly.

**Comment by jtaaa** [comment]
`createFactorySellOrder` has been deprecated due to some differences between wyvern and seaport, and because seaport unlocks better ways to accomplish the same (or similar) results. We've removed the doc page that suggests using this method and its implementation will be removed from the SDK in a future release.

Soon we will publish a new factory contract example and tutorial that is compatible with seaport. Sorry for the confusion.

**Comment by Utcha** [comment]
@jtaaa Hi I am also getting the same error when using createSellOrder.
When can you fix this?

**Comment by ssl** [comment]
> @cto-aarchik then you have to update your SDK. Maybe your old version is still in node_modules? You also have to import `OpenSeaSDK` .
> 
> ```js
> import { OpenSeaSDK, Network } from 'opensea-js'
> ```

This is how i fixed createSellOrder not working. Updating opensea-js to 4.0.x and then changing the import 'OpenSeaPort' to 'OpenSeaSDK'. Works fine now.

**Comment by coxlabz** [comment]
> > @cto-aarchik then you have to update your SDK. Maybe your old version is still in node_modules? You also have to import `OpenSeaSDK` .
> > ```js
> > import { OpenSeaSDK, Network } from 'opensea-js'
> > ```
> 
> This is how i fixed createSellOrder not working. Updating opensea-js to 4.0.x and then changing the import 'OpenSeaPort' to 'OpenSeaSDK'. Works fine now.

Hi there, would you mind sharing the node version that you're running on?

**Comment by Lebski** [comment]
I'm using Node v16

**Comment by laubsauger** [comment]
> 



> > @cto-aarchik then you have to update your SDK. Maybe your old version is still in node_modules? You also have to import `OpenSeaSDK` .
> > ```js
> > import { OpenSeaSDK, Network } from 'opensea-js'
> > ```
> 
> This is how i fixed createSellOrder not working. Updating opensea-js to 4.0.x and then changing the import 'OpenSeaPort' to 'OpenSeaSDK'. Works fine now.

Just tested this and unfortunately this does not fix the original issue with `createFactorySellOrder`. 
Mentioned error persists.

**Comment by aaltergot** [comment]
Experiencing same issue. What's the reason behind the API deprecation? There is no chance it'll be un-deprecated, right? And also there is no substitution to this functionality planned.

**Comment by laubsauger** [comment]
> Experiencing same issue. What's the reason behind the API deprecation? There is no chance it'll be un-deprecated, right? And also there is no substitution to this functionality planned.

It's only been like two weeks. Still no documentation or anything really. 
Guess it's time to move.

**Comment by Lebski** [comment]
> Experiencing same issue. What's the reason behind the API deprecation? There is no chance it'll be un-deprecated, right? And also there is no substitution to this functionality planned.

I think they changed the underlying protocol. Which also means their own contract won't work with new API. And no I don't see a change that this is coming back. 
They announced that they will bring back the factory but no examples etc. are available.

**Comment by laubsauger** [comment]
> > Experiencing same issue. What's the reason behind the API deprecation? There is no chance it'll be un-deprecated, right? And also there is no substitution to this functionality planned.
> 
> I think they changed the underlying protocol. Which also means their own contract won't work with new API. And I don't see a chance that this is coming back. They announced that they will bring back the factory but no examples etc. are available.

Did you find any alternative to create lazy mint sells from a factory? Different approach on opensea or on a different platform?

**Comment by metatonks** [comment]
@laubsauger Hi, did you find any documentation on a new "factory" for lazy mint. (I had build around this and now functionality seems to have been pulled)

**Comment by laubsauger** [comment]
@metatonks No. We got really screwed up by this change, having built up the setup, rolling the marketing etc only to have this pulled without replacement. 
Couldn't get something comparable to work on LooksRare and Rarible just yet.
Might have to pull the whole thing and put up a lame self-mint. 

Bright side is we wouldn't have to hand over service fees to OpenSea :P

**Comment by Lebski** [comment]
> Did you find any alternative to create lazy mint sells from a factory? Different approach on opensea or on a different platform?

Since the change happend literally before our scheduled mint we came up with the following solution: 

1. We created an ERC1155 on the OpenSea Frontend, which allowed us to use lazy mint
2. We created custom orders (whitelists) with the API and the `createSellOrderLegacyWyvern` function 
3. After the sale we made a snapshot of token owners with the moralis API 
4. We AirDropped the token via basic ERC721 smart contract

**Comment by metatonks** [comment]
@jtaaa Hi, any estimated timeline on an update factory contract example? Or some documents or hints on how to make this work? Factory contract seems fine I just need a way to sell the options. Thank you.

**Comment by Deathwing** [comment]
I finally got a working factory contract out but the missing createFactorySellOrders is ruining everything. I mean I can sell 1 option at a time via the web interface, but that is not a great solution at all :)
I even tried createSellOrder with quantity > 1, but that just resulted in 'The offerer does not have the amount needed to create or fulfill.', while doing it with quantity == 1, I got '[InternalError: Internal error] { code: -32603 }', so it seems no way around ;(

**Comment by Lebski** [comment]
@Deathwing would you mind sharing the factory part of the contract with me? 
Our sale is already over but I'm curious how you made it work...

**Comment by Deathwing** [comment]
@Lebski Sure, I also found a way to even get the open-sea API working, so take a look:
https://gist.github.com/Deathwing/b49c03c465c17312f8affc536b5ea64d
