### ISSUE TITLE
Error: invalid BigNumber value

### ISSUE THREAD

**Issue by jackwolt** [ProjectOpenSea/opensea-js#734]
Started getting this error today, on openseaSDK.createSellOrder() method with Node 16.14.0

```
await openseaSDK.createSellOrder({
        asset: {
             tokenId: item.id,
        },
        startAmount: item.startAmount, // 1.5
        endAmount: item.endAmount,  // 1.35  
        ...

        /** Getting id, prices - from my "item" array  */
 });
```

My current package.json
```
"dependencies": {
    "yarn": "^1.22.19",
    "@0x/subproviders": "^7.0.0",
    "@truffle/hdwallet-provider": "^2.0.14",
    "express": "^4.18.1",
    "opensea-js": "^4.0.8",
    "web3": "^1.7.5"
  }
```

Full error information.
```
Error: invalid BigNumber value (argument="value", value=undefined, code=INVALID_ARGUMENT, version=bignumber/5.6.2)
    at Logger.makeError (/app/node_modules/@ethersproject/logger/lib/index.js:233:21)
    at Logger.throwError (/app/node_modules/@ethersproject/logger/lib/index.js:242:20)
    at Logger.throwArgumentError (/app/node_modules/@ethersproject/logger/lib/index.js:245:21)
    at Function.BigNumber.from (/app/node_modules/@ethersproject/bignumber/lib/bignumber.js:239:23)
    at toBN (/app/node_modules/@ethersproject/bignumber/lib/bignumber.js:292:25)
    at BigNumber.add (/app/node_modules/@ethersproject/bignumber/lib/bignumber.js:57:43)
    at /app/node_modules/@opensea/seaport-js/lib/utils/order.js:151:43
    at Array.reduce (<anonymous>)
    at totalItemsAmount (/app/node_modules/@opensea/seaport-js/lib/utils/order.js:147:10)
    at Seaport.<anonymous> (/app/node_modules/@opensea/seaport-js/lib/seaport.js:285:76)
    at step (/app/node_modules/@opensea/seaport-js/lib/seaport.js:44:23)
    at Object.next (/app/node_modules/@opensea/seaport-js/lib/seaport.js:25:53)
    at fulfilled (/app/node_modules/@opensea/seaport-js/lib/seaport.js:16:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
        reason: 'invalid BigNumber value',
        code: 'INVALID_ARGUMENT',
        argument: 'value',
        value: undefined
    }
```

**Comment by szokeptr** [comment]
Also getting this. Seems like a bug was introduced when adding support for multiple creator fees in #724 and an array of consideration items is passed as consideration item in `createBuyOrder` and `createSellOrder`.

**Comment by soqt** [comment]
I have the same problem. I was using 4.0.7 and everything was fine. But after I upgraded to 4.0.9 & downgrade to 4.0.7, this problem appears.

**Comment by jackwolt** [comment]
> Also getting this. Seems like a bug was introduced when adding support for multiple creator fees in #724 and an array of consideration items is passed as consideration item in `createBuyOrder` and `createSellOrder`.
> 
> Later edit: version 4.0.7 works correctly.

Yep 4.0.7 works correctly, thank you. I don't think it's worth closing this issue as it's still a problem in latest versions.

**Comment by jackwolt** [comment]
> I have the same problem. I was using 4.0.7 and everything was fine. But after I upgraded to 4.0.9 & downgrade to 4.0.7, this problem appears.

Try specified in your package file "opensea-js": "4.0.7", without ^ symbol.

**Comment by soqt** [comment]
> > I have the same problem. I was using 4.0.7 and everything was fine. But after I upgraded to 4.0.9 & downgrade to 4.0.7, this problem appears.
> 
> Try specified in your package file "opensea-js": "4.0.7", without ^ symbol.

Oh right. I removed ^ symbol and everything works! Thank you!

**Comment by 0xIsshiki** [comment]
I thought I fixed this in https://github.com/ProjectOpenSea/opensea-js/pull/731, but there was more that needed to be done. This should be fixed in https://github.com/ProjectOpenSea/opensea-js/pull/740.

**Comment by jackwolt** [comment]
> I thought I fixed this in #731, but there was more that needed to be done. This should be fixed in #740.

Thank you very much! Waiting for a fix

**Comment by sunwrobert** [comment]
This will be fixed in #746

**Comment by josmontes** [comment]
Any updates on this? I'm still experiencing this same error:
```
invalid BigNumber value (argument="value", value=undefined, code=INVALID_ARGUMENT, version=bignumber/5.6.2)
    at Logger.makeError (index.js?a54a:219:1)
    at Logger.throwError (index.js?a54a:228:1)
    at Logger.throwArgumentError (index.js?a54a:231:1)
    at BigNumber.from (bignumber.js?9ea3:233:1)
    at toBN (bignumber.js?9ea3:284:1)
    at BigNumber.add (bignumber.js?9ea3:51:1)
    at eval (order.js?fe19:152:1)
    at Array.reduce (<anonymous>)
    at totalItemsAmount (order.js?fe19:148:1)
    at Seaport.eval (seaport.js?8086:286:1)
    at step (seaport.js?8086:44:1)
    at Object.eval [as next] (seaport.js?8086:25:46)
    at fulfilled (seaport.js?8086:16:43)
    ```

**Comment by sunwrobert** [comment]
> This will be fixed in #746

you're getting that on version 4.0.11?

**Comment by josmontes** [comment]
> > This will be fixed in #746
> 
> @josmontes you're getting that on version 4.0.11?

Yes! I tried with multiple collections and got the same error. I had to go back to 4.0.7 since it was the last working version that i know of. Ill share with you the complete function call if you need it

**Comment by creed-dev** [comment]
> > This will be fixed in #746
> 
> @josmontes you're getting that on version 4.0.11?

I also get this error on version 4.0.11.

**Comment by ZionNFT** [comment]
Getting this also @sunwrobert. Happy to provide you with more information here...

**Comment by sunwrobert** [comment]
It should finally be fixed now in 4.0.12. Thanks for your patience everyone.

**Comment by jackwolt** [comment]
> It should finally be fixed now in 4.0.12. Thanks for your patience everyone.

Its look like work fine with 4.0.12! Thank you, hope we can close this issue now?

**Comment by yieldmaxi** [comment]
Emm I still have this issue on 4.0.12

**Comment by creed-dev** [comment]
> Emm I still have this issue on 4.0.12

Sometimes I get the same error, but very rarely. Version - 4.0.12.
